openapi: 3.0.0

info:
  title: OAuth Example
  version: "1.0"

servers:
  - url: /api

paths:
  /mangum:
    post:
      summary: Mangum endpoint
      operationId: api.demo.post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: string
              required:
                - payload
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object


components:
  securitySchemes:
    oauth2:
      type: oauth2
      #      x-tokenInfoUrl: http://localhost:7979/tokeninfo
      #      or set TOKENINFO_URL environment variable

      #      x-tokenInfoFunc: api.auth.token_info
      #      or set TOKENINFO_FUNC environment variable
      flows:
        implicit:
          authorizationUrl: https://example.com/oauth2/dialog
          # the token info URL is hardcoded for our mock_tokeninfo.py script
          # you can also pass it as an environment variable TOKENINFO_URL
          scopes:
            uid: Unique identifier of the user accessing the service.
